In [4]:
import numpy as np
list = [1,2,3]
list

[1, 2, 3]

In [5]:
np.array(list)

array([1, 2, 3])

In [6]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(5,21,5)

array([ 5, 10, 15, 20])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.zeros((4,2,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [27]:
np.eye(5,10,5)

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])