In [1]:
import numpy as np

In [2]:
inputBanyak = int(input('Banyak Data :'))
inputMulai = int(input('Mulai :' ))
inputSelesai = int(input('Selesai :'))

In [20]:
arr=np.random.randint(inputMulai,inputSelesai,inputBanyak)
np.array(arr)

array([11, 34, 49, 12, 16, 48,  6, 29, 39, 27, 37, 34, 22, 24, 36, 15])

In [22]:
twoDarr=arr.reshape(4,4)
np.array(twoDarr)

array([[11, 34, 49, 12],
       [16, 48,  6, 29],
       [39, 27, 37, 34],
       [22, 24, 36, 15]])

In [23]:
twoDarr[:, ::-1]

array([[12, 49, 34, 11],
       [29,  6, 48, 16],
       [34, 37, 27, 39],
       [15, 36, 24, 22]])